# Generated by Django 5.0.7 on 2025-09-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if operation failed'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, default=dict, help_text='New values after change'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, default=dict, help_text='Previous values before change'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='project_slug',
            field=models.CharField(blank=True, help_text='Project slug at time of action', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='referer',
            field=models.TextField(blank=True, help_text='HTTP referer'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, help_text='HTTP method', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.TextField(blank=True, help_text='URL path of the request'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key for tracking user sessions', max_length=40),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='success',
            field=models.BooleanField(default=True, help_text='Whether the operation succeeded'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_object_id',
            field=models.CharField(blank=True, help_text='ID of target object', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_object_repr',
            field=models.TextField(blank=True, help_text='String representation of target object'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='target_object_type',
            field=models.CharField(blank=True, help_text='Model name of target object', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Email at time of action', max_length=254),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, help_text='Username at time of action (preserved even if user deleted)', max_length=150),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create_project', 'Create Project'), ('update_project', 'Update Project'), ('delete_project', 'Delete Project'), ('add_user', 'Add User'), ('remove_user', 'Remove User'), ('change_role', 'Change Role'), ('grant_privilege', 'Grant Privilege'), ('revoke_privilege', 'Revoke Privilege'), ('enable_module', 'Enable Module'), ('disable_module', 'Disable Module'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('create_record', 'Create Record'), ('update_record', 'Update Record'), ('delete_record', 'Delete Record'), ('view_record', 'View Record'), ('export_data', 'Export Data'), ('import_data', 'Import Data'), ('bulk_operation', 'Bulk Operation'), ('admin_login', 'Admin Login'), ('system_config_change', 'System Config Change'), ('backup_created', 'Backup Created'), ('backup_restored', 'Backup Restored'), ('maintenance_mode', 'Maintenance Mode'), ('project_access', 'Project Access'), ('cross_project_access', 'Cross Project Access'), ('api_access', 'API Access'), ('unauthorized_access_attempt', 'Unauthorized Access Attempt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.JSONField(default=dict, help_text='Additional context and metadata'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
