# Generated by Django 5.0.7 on 2025-09-12 16:06

from django.db import migrations, models


def remove_privilege_tables(apps, schema_editor):
    """
    Safely remove privilege-related tables if they exist.
    """
    from django.db import connection
    cursor = connection.cursor()
    
    # List of tables to drop
    tables_to_drop = [
        'control_plane_globalprivilegeassignment',
        'control_plane_projectprivilegeassignment',
        'control_plane_privilegeregistry',
    ]
    
    for table in tables_to_drop:
        try:
            cursor.execute(f"DROP TABLE IF EXISTS {table}")
        except Exception as e:
            print(f"Could not drop table {table}: {e}")


def reverse_remove_privilege_tables(apps, schema_editor):
    """
    This migration cannot be reversed as we're dropping tables.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0002_auditlog_error_message_auditlog_new_values_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_privilege_tables, reverse_remove_privilege_tables),
        migrations.AlterModelOptions(
            name='roletype',
            options={'ordering': ['level'], 'verbose_name': 'Project Role Type', 'verbose_name_plural': 'Project Role Types'},
        ),
        migrations.AlterField(
            model_name='roletype',
            name='description',
            field=models.TextField(help_text='Role description for documentation'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='display_name',
            field=models.CharField(help_text='Human-readable role name', max_length=100),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='level',
            field=models.IntegerField(help_text='Display hierarchy level (lower=higher in hierarchy)'),
        ),
        migrations.AlterField(
            model_name='roletype',
            name='name',
            field=models.CharField(help_text="Role identifier (e.g., 'project_admin', 'operator')", max_length=20, unique=True),
        ),
    ]