# Generated by Django 5.0.7 on 2025-08-12 04:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_traspaso_traspasodetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('valor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NotaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=16, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('obra', models.CharField(help_text='Obra/Proyecto', max_length=150)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.almacen')),
            ],
            options={
                'verbose_name': 'Nota de pedido',
                'verbose_name_plural': 'Notas de pedido',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaPedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Si no eliges material, escribe la descripción manual', max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('precio', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.material')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.notapedido')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidad')),
            ],
        ),
    ]
