# Generated by Django 5.0.7 on 2025-09-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_consecutivo_project_notapedido_project_and_more'),
    ]

    operations = [
        # Drop unused tables
        migrations.RunSQL(
            "DROP TABLE IF EXISTS inventario_consecutivo;",
            reverse_sql="CREATE TABLE inventario_consecutivo (id int);"  # Placeholder reverse
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS inventario_notapedidodetalle;",
            reverse_sql="CREATE TABLE inventario_notapedidodetalle (id int);"  # Placeholder reverse
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS inventario_notapedido;",
            reverse_sql="CREATE TABLE inventario_notapedido (id int);"  # Placeholder reverse
        ),
    ]
