# Generated by Django 5.0.7 on 2025-08-27 12:12

import django.db.models.deletion
import saas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projectmodule',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='projectmodule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user_limit',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(default=saas.models.default_invite_expires_at),
        ),
        migrations.AlterField(
            model_name='invite',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='saas.project'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='invite',
            name='token',
            field=models.CharField(db_index=True, default=saas.models.default_invite_token, max_length=52, unique=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='saas.project'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='operator', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_modules', to='saas.project'),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_modules', to='saas.module'),
        ),
        migrations.AddConstraint(
            model_name='projectmodule',
            constraint=models.UniqueConstraint(fields=('project', 'module'), name='uniq_project_module'),
        ),
    ]
