# Generated by Django 5.0.7 on 2025-09-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_groupproxy_userproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('allow_system_admin_groups', models.BooleanField(default=False, help_text='Permitir que system_admin gestione Grupos (auth.Group).')),
                ('allow_system_admin_modules', models.BooleanField(default=False, help_text='Permitir que system_admin gestione Módulos (saas.Module).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de Administración',
                'verbose_name_plural': 'Política de Administración',
            },
        ),
    ]
